### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by nicmacor** [xpmatteo/birthday-greetings-kata#3]
Soy de la universidad Espol del Ecuador y como tarea nos mandaron a buscar repositorios a los cuales identificar los code smells y hacer refactoring. Me parece haber encontrados unos en su codigo.

1.-Long Method 

Este code smell se da cuando un método es muy largo, hace mas difícil comprender el código y lo que hace el método. En este caso se encuentra en BirthdayService en sendGreetings. 
Refactoring: Utilizaremos Extract Method lo cual nos ayudara a extraer líneas de este método para que sea mas corto, mas fácil de leer y entender. 

 ![Picture1](https://user-images.githubusercontent.com/93363380/185834071-6b67c0ea-d389-4490-ad0a-12e90c39f714.png)

2.-Long parameter list 

Este code smell se encuentra en BirthdayService en el método sendMessage ya que tiene 6 parametros. Ocurre porque muchas cosas están metidas en el mismo método, es algo complicado entender el método con tantos parámetros por lo que aplicaremos un método de refactorización que hará que se vea mejor. 
Refactoring: Usaremos Introduce Parameter Object que nos permitirá unir algunos de los parámetros y hacerlos un objeto con dichos parámetros. Así podemos enviar el objeto en vez de enviar tantos parámetros al método. Esto hará que el código sea mas legible. 

![Picture2](https://user-images.githubusercontent.com/93363380/185834133-f89c2c71-0ea7-4a18-993e-516e918e591c.png)

**Comment by xpmatteo** [comment]
Hola Nic,

Ben fatto! Questo repository è fatto apposta per esercitarsi nel
refactoring.

Per questo non accetto pull request che rimuovono smell; il punto è proprio
di avere un codice con vari smell da rimuovere a scopo didattico
